#! /bin/sh

set -e

DESC="crond"
NAME=crond
DAEMON=/usr/sbin/$NAME

case "$1" in
  start)
    printf "Starting $DESC: "
    start-stop-daemon -S -x -b --exec $DAEMON -- -l 9 -c /etc/cron/crontabs
    echo "OK"
    ;;
  stop)
    printf "Stopping $DESC: "
    start-stop-daemon -K -x $NAME
    echo "OK"
    ;;
  restart|force-reload)
    echo "Restarting $DESC: "
    $0 stop
    sleep 1
    $0 start
    echo ""
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
