#! /bin/sh

set -e

DESC="aplay"

case "$1" in
  start)
	printf "Starting $DESC: "
	amixer sset Speaker 100% > /dev/null 2>&1
	aplay /usr/share/sounds/alsa/Noise.wav > /dev/null 2>&1 &
	echo "OK"
	;;
  stop)
	printf "Stopping $DESC: "
	echo "OK"
	;;
  restart|force-reload)
	echo "Restarting $DESC: "
	$0 stop
	sleep 1
	$0 start
	echo ""
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
